name: markus bot greet

on:
  schedule:
    - cron: '15,45 * * * *'

jobs:
  greet-user:
    name: Greet user
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v2
      - name: 'Run action'
        run: |
          node greet.js
        env:
          KB_USERNAME: ${{ secrets.KB_USERNAME }}
          KB_PAPERKEY: ${{ secrets.KB_PAPERKEY }}
