name: markus bot greet

on:
  schedule:
    - cron: '15,45 * * * *'

jobs:
  greet-user:
    name: Greet user
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Run action'
        uses: docker://keybaseio/client:stable-node-slim
      - run: npm install
      - run: npm greet
        env:
          KB_USERNAME: ${{ secrets.KB_USERNAME }}
          KB_PAPERKEY: ${{ secrets.KB_PAPERKEY }}
