name: markus bot greet

on:
  push:
    branch:
      - master
  schedule:
    - cron: '0 * * * *'

jobs:
  greet-user:
    name: Greet user
    runs-on: ubuntu-latest
    container:
      image: keybaseio/client:stable-node-slim
    steps:
      - uses: actions/checkout@v2
      - name: 'Run action'
        run: |
          npm install
          npm run greet
        env:
          KB_USERNAME: ${{ secrets.KB_USERNAME }}
          KB_PAPERKEY: ${{ secrets.KB_PAPERKEY }}
