name: markus bot greet

on:
  push:
    branch:
      - master

jobs:
  greet-user:
    name: Greet user
    runs-on: ubuntu-latest
    steps:
      # ... steps where you do something here ...
      - name: Build Live Notification
        env:
          JSON_MSG: >-
            {
                "method": "send",
                "params": {
                    "options": {"channel": {"name": "mark854"},
                    "message": {"body": "Hello Mark"}}
                }
            }            
        run: echo $JSON_MSG > message.json
      - name: Keybase Notification
        uses: docker://keybaseio/client:stable
        env:
          KEYBASE_USERNAME: ${{ secrets.KB_USERNAME }}
          KEYBASE_PAPERKEY: ${{ secrets.KB_PAPERKEY }}
          KEYBASE_SERVICE: "1"
        with:
          args: keybase chat api -i message.json